export interface Currency {
    code: string;
    currency: string;
    symbol: string;
    country: string;
}

export const CURRENCIES: Currency[] = [
    { country: "United Arab Emirates", currency: "United Arab Emirates Dirham", code: "AED", symbol: "د.إ" },
    { country: "Afghanistan", currency: "Afghanistan Afghani", code: "AFN", symbol: "؋" },
    { country: "Albania", currency: "Albanian Lek", code: "ALL", symbol: "L" },
    { country: "Armenia", currency: "Armenian Dram", code: "AMD", symbol: "֏" },
    { country: "Curaçao & Sint Maarten", currency: "Netherlands Antillean Guilder", code: "ANG", symbol: "ƒ" },
    { country: "Angola", currency: "Angolan Kwanza", code: "AOA", symbol: "Kz" },
    { country: "Argentina", currency: "Argentine Peso", code: "ARS", symbol: "$" },
    { country: "Australia", currency: "Australian Dollar", code: "AUD", symbol: "$" },
    { country: "Aruba", currency: "Aruban Florin", code: "AWG", symbol: "ƒ" },
    { country: "Azerbaijan", currency: "Azerbaijani Manat", code: "AZN", symbol: "₼" },
    { country: "Bosnia and Herzegovina", currency: "Bosnia and Herzegovina Convertible Mark", code: "BAM", symbol: "KM" },
    { country: "Barbados", currency: "Barbadian Dollar", code: "BBD", symbol: "$" },
    { country: "Bangladesh", currency: "Bangladeshi Taka", code: "BDT", symbol: "৳" },
    { country: "Bulgaria", currency: "Bulgarian Lev", code: "BGN", symbol: "лв" },
    { country: "Bahrain", currency: "Bahraini Dinar", code: "BHD", symbol: ".د.ب" },
    { country: "Burundi", currency: "Burundian Franc", code: "BIF", symbol: "FBu" },
    { country: "Bermuda", currency: "Bermudian Dollar", code: "BMD", symbol: "$" },
    { country: "Brunei", currency: "Brunei Dollar", code: "BND", symbol: "$" },
    { country: "Bolivia", currency: "Bolivian Boliviano", code: "BOB", symbol: "$b" },
    { country: "Brazil", currency: "Brazilian Real", code: "BRL", symbol: "R$" },
    { country: "Bahamas", currency: "Bahamian Dollar", code: "BSD", symbol: "$" },
    { country: "Bhutan", currency: "Bhutanese Ngultrum", code: "BTN", symbol: "Nu." },
    { country: "Botswana", currency: "Botswanan Pula", code: "BWP", symbol: "P" },
    { country: "Belarus", currency: "Belarusian Ruble", code: "BYN", symbol: "Br" },
    { country: "Belize", currency: "Belize Dollar", code: "BZD", symbol: "BZ$" },
    { country: "Canada", currency: "Canadian Dollar", code: "CAD", symbol: "$" },
    { country: "Democratic Republic of the Congo", currency: "Congolese Franc", code: "CDF", symbol: "FC" },
    { country: "Switzerland", currency: "Swiss Franc", code: "CHF", symbol: "CHF" },
    { country: "Chile", currency: "Chilean Peso", code: "CLP", symbol: "$" },
    { country: "China", currency: "Chinese Yuan", code: "CNY", symbol: "¥" },
    { country: "Colombia", currency: "Colombian Peso", code: "COP", symbol: "$" },
    { country: "Costa Rica", currency: "Costa Rican Colón", code: "CRC", symbol: "₡" },
    { country: "Cuba", currency: "Cuban Peso", code: "CUP", symbol: "₱" },
    { country: "Cape Verde", currency: "Cape Verdean Escudo", code: "CVE", symbol: "$" },
    { country: "Czech Republic", currency: "Czech Koruna", code: "CZK", symbol: "Kč" },
    { country: "Djibouti", currency: "Djiboutian Franc", code: "DJF", symbol: "Fdj" },
    { country: "Denmark", currency: "Danish Krone", code: "DKK", symbol: "kr" },
    { country: "Dominican Republic", currency: "Dominican Peso", code: "DOP", symbol: "RD$" },
    { country: "Algeria", currency: "Algerian Dinar", code: "DZD", symbol: "د.ج" },
    { country: "Egypt", currency: "Egyptian Pound", code: "EGP", symbol: "£" },
    { country: "Eritrea", currency: "Eritrean Nakfa", code: "ERN", symbol: "Nfk" },
    { country: "Ethiopia", currency: "Ethiopian Birr", code: "ETB", symbol: "Br" },
    { country: "Eurozone", currency: "Euro", code: "EUR", symbol: "€" },
    { country: "Fiji", currency: "Fijian Dollar", code: "FJD", symbol: "$" },
    { country: "Falkland Islands", currency: "Falkland Islands Pound", code: "FKP", symbol: "£" },
    { country: "United Kingdom", currency: "British Pound Sterling", code: "GBP", symbol: "£" },
    { country: "Georgia", currency: "Georgian Lari", code: "GEL", symbol: "₾" },
    { country: "Ghana", currency: "Ghanaian Cedi", code: "GHS", symbol: "¢" },
    { country: "Gibraltar", currency: "Gibraltar Pound", code: "GIP", symbol: "£" },
    { country: "Gambia", currency: "Gambian Dalasi", code: "GMD", symbol: "D" },
    { country: "Guinea", currency: "Guinean Franc", code: "GNF", symbol: "FG" },
    { country: "Guatemala", currency: "Guatemalan Quetzal", code: "GTQ", symbol: "Q" },
    { country: "Guyana", currency: "Guyanese Dollar", code: "GYD", symbol: "$" },
    { country: "Hong Kong", currency: "Hong Kong Dollar", code: "HKD", symbol: "$" },
    { country: "Honduras", currency: "Honduran Lempira", code: "HNL", symbol: "L" },
    { country: "Croatia", currency: "Croatian Kuna", code: "HRK", symbol: "kn" },
    { country: "Haiti", currency: "Haitian Gourde", code: "HTG", symbol: "G" },
    { country: "Hungary", currency: "Hungarian Forint", code: "HUF", symbol: "Ft" },
    { country: "Indonesia", currency: "Indonesian Rupiah", code: "IDR", symbol: "Rp" },
    { country: "Israel", currency: "Israeli New Shekel", code: "ILS", symbol: "₪" },
    { country: "India", currency: "Indian Rupee", code: "INR", symbol: "₹" },
    { country: "Iraq", currency: "Iraqi Dinar", code: "IQD", symbol: "د.ع" },
    { country: "Iran", currency: "Iranian Rial", code: "IRR", symbol: "Profiles" },
    { country: "Iceland", currency: "Icelandic Króna", code: "ISK", symbol: "kr" },
    { country: "Jamaica", currency: "Jamaican Dollar", code: "JMD", symbol: "J$" },
    { country: "Jordan", currency: "Jordanian Dinar", code: "JOD", symbol: "د.ا" },
    { country: "Japan", currency: "Japanese Yen", code: "JPY", symbol: "¥" },
    { country: "Kenya", currency: "Kenyan Shilling", code: "KES", symbol: "KSh" },
    { country: "Kyrgyzstan", currency: "Kyrgyzstani Som", code: "KGS", symbol: "лв" },
    { country: "Cambodia", currency: "Cambodian Riel", code: "KHR", symbol: "៛" },
    { country: "Comoros", currency: "Comorian Franc", code: "KMF", symbol: "CF" },
    { country: "North Korea", currency: "North Korean Won", code: "₩", symbol:"W" },
    { country: "South Korea", currency: "South Korean Won", code: "KRW", symbol: "₩" },
    { country: "Kuwait", currency: "Kuwaiti Dinar", code: "KWD", symbol: "د.ك" },
    { country: "Cayman Islands", currency: "Cayman Islands Dollar", code: "KYD", symbol: "$" },
    { country: "Kazakhstan", currency: "Kazakhstani Tenge", code: "KZT", symbol: "₸" },
    { country: "Laos", currency: "Laotian Kip", code: "LAK", symbol: "₭" },
    { country: "Lebanon", currency: "Lebanese Pound", code: "LBP", symbol: "ل.ل" },
    { country: "Sri Lanka", currency: "Sri Lankan Rupee", code: "LKR", symbol: "₨" },
    { country: "Liberia", currency: "Liberian Dollar", code: "LRD", symbol: "$" },
    { country: "Lesotho", currency: "Lesotho Loti", code: "LSL", symbol: "M" },
    { country: "Libya", currency: "Libyan Dinar", code: "LYD", symbol: "د.ل" },
    { country: "Morocco", currency: "Moroccan Dirham", code: "MAD", symbol: "د.م." },
    { country: "Moldova", currency: "Moldovan Leu", code: "MDL", symbol: "L" },
    { country: "Madagascar", currency: "Malagasy Ariary", code: "MGA", symbol: "Ar" },
    { country: "North Macedonia", currency: "Macedonian Denar", code: "MKD", symbol: "ден" },
    { country: "Myanmar", currency: "Myanmar Kyat", code: "MMK", symbol: "K" },
    { country: "Mongolia", currency: "Mongolian Tugrik", code: "MNT", symbol: "₮" },
    { country: "Macau", currency: "Macanese Pataca", code: "MOP$", symbol: "MOP$" },
    { country: "Mauritania", currency: "Mauritanian Ouguiya", code: "MRU", symbol: "UM" },
    { country: "Mauritius", currency: "Mauritian Rupee", code: "MUR", symbol: "₨" },
    { country: "Maldives", currency: "Maldivian Rufiyaa", code: "MVR", symbol: "Rf" },
    { country: "Malawi", currency: "Malawian Kwacha", code: "MWK", symbol: "MK" },
    { country: "Mexico", currency: "Mexican Peso", code: "MXN", symbol: "$" },
    { country: "Malaysia", currency: "Malaysian Ringgit", code: "MYR", symbol: "RM" },
    { country: "Mozambique", currency: "Mozambican Metical", code: "MZN", symbol: "MT" },
    { country: "Namibia", currency: "Namibian Dollar", code: "NAD", symbol: "$" },
    { country: "Nigeria", currency: "Nigerian Naira", code: "NGN", symbol: "₦" },
    { country: "Nicaragua", currency: "Nicaraguan Córdoba", code: "NIO", symbol: "C$" },
    { country: "Norway", currency: "Norwegian Krone", code: "NOK", symbol: "kr" },
    { country: "Nepal", currency: "Nepalese Rupee", code: "NPR", symbol: "₨" },
    { country: "New Zealand", currency: "New Zealand Dollar", code: "NZD", symbol: "$" },
    { country: "Oman", currency: "Omani Rial", code: "OMR", symbol: "ر.ع." },
    { country: "Panama", currency: "Panamanian Balboa", code: "PAB", symbol: "B/." },
    { country: "Peru", currency: "Peruvian Sol", code: "PEN", symbol: "S/." },
    { country: "Papua New Guinea", currency: "Papua New Guinean Kina", code: "PGK", symbol: "K" },
    { country: "Philippines", currency: "Philippine Peso", code: "PHP", symbol: "₱" },
    { country: "Pakistan", currency: "Pakistani Rupee", code: "PKR", symbol: "₨" },
    { country: "Poland", currency: "Polish Zloty", code: "PLN", symbol: "zł" },
    { country: "Paraguay", currency: "Paraguayan Guaraní", code: "PYG", symbol: "Gs" },
    { country: "Qatar", currency: "Qatari Rial", code: "QAR", symbol: "ر.ق" },
    { country: "Romania", currency: "Romanian Leu", code: "RON", symbol: "lei" },
    { country: "Serbia", currency: "Serbian Dinar", code: "RSD", symbol: "дин." },
    { country: "Russia", currency: "Russian Ruble", code: "RUB", symbol: "₽" },
    { country: "Rwanda", currency: "Rwandan Franc", code: "RWF", symbol: "FRw" },
    { country: "Saudi Arabia", currency: "Saudi Riyal", code: "SAR", symbol: "ر.س" },
    { country: "Solomon Islands", currency: "Solomon Islands Dollar", code: "SBD", symbol: "$" },
    { country: "Seychelles", currency: "Seychellois Rupee", code: "SCR", symbol: "₨" },
    { country: "Sudan", currency: "Sudanese Pound", code: "SDG", symbol: "ج.س." },
    { country: "Sweden", currency: "Swedish Krona", code: "SEK", symbol: "kr" },
    { country: "Singapore", currency: "Singapore Dollar", code: "SGD", symbol: "$" },
    { country: "Saint Helena", currency: "Saint Helena Pound", code: "SHP", symbol: "£" },
    { country: "Sierra Leone", currency: "Sierra Leonean Leone", code: "SLE", symbol: "Le" },
    { country: "Somalia", currency: "Somali Shilling", code: "SOS", symbol: "S" },
    { country: "Suriname", currency: "Surinamese Dollar", code: "SRD", symbol: "$" },
    { country: "São Tomé and Príncipe", currency: "São Tomé and Príncipe Dobra", code: "STN", symbol: "Db" },
    { country: "El Salvador", currency: "Salvadoran Colón", code: "SVC", symbol: "$" },
    { country: "Syria", currency: "Syrian Pound", code: "SYP", symbol: "£" },
    { country: "Eswatini", currency: "Swazi Lilangeni", code: "SZL", symbol: "L" },
    { country: "Thailand", currency: "Thai Baht", code: "THB", symbol: "฿" },
    { country: "Tajikistan", currency: "Tajikistani Somoni", code: "TJS", symbol: "SM" },
    { country: "Turkmenistan", currency: "Turkmenistani Manat", code: "TMT", symbol: "T" },
    { country: "Tunisia", currency: "Tunisian Dinar", code: "TND", symbol: "د.ت" },
    { country: "Tonga", currency: "Tongan Paʻanga", code: "TOP", symbol: "T$" },
    { country: "Turkey", currency: "Turkish Lira", code: "TRY", symbol: "₺" },
    { country: "Trinidad and Tobago", currency: "Trinidad and Tobago Dollar", code: "TTD", symbol: "TT$" },
    { country: "Taiwan", currency: "New Taiwan Dollar", code: "TWD", symbol: "NT$" },
    { country: "Tanzania", currency: "Tanzanian Shilling", code: "TZS", symbol: "TSh" },
    { country: "Ukraine", currency: "Ukrainian Hryvnia", code: "UAH", symbol: "₴" },
    { country: "Uganda", currency: "Ugandan Shilling", code: "UGX", symbol: "USh" },
    { country: "United States", currency: "US Dollar", code: "USD", symbol: "$" },
    { country: "Uruguay", currency: "Uruguayan Peso", code: "$U", symbol: "$u" },
    { country: "Uzbekistan", currency: "Uzbekistan Som", code: "UZS", symbol: "лв" },
    { country: "Venezuela", currency: "Venezuelan Bolívar Soberano", code: "VES", symbol: "Bs.S" },
    { country: "Vietnam", currency: "Vietnamese Dong", code: "VND", symbol: "₫" },
    { country: "Vanuatu", currency: "Vanuatu Vatu", code: "VUV", symbol: "VT" },
    { country: "Samoa", currency: "Samoan Tala", code: "WST", symbol: "WS$" },
    { country: "Central African Republic", currency: "CFA Franc BEAC", code: "XAF", symbol: "FCFA" },
    { country: "East Caribbean States", currency: "East Caribbean Dollar", code: "XCD", symbol: "$" },
    { country: "West African States", currency: "CFA Franc BCEAO", code: "XOF", symbol: "CFA" },
    { country: "French Polynesia", currency: "CFP Franc", code: "XPF", symbol: "₣" },
    { country: "Yemen", currency: "Yemeni Rial", code: "YER", symbol: "﷼" },
    { country: "South Africa", currency: "South African Rand", code: "ZAR", symbol: "R" },
    { country: "Zambia", currency: "Zambian Kwacha", code: "ZMW", symbol: "ZK" },
    { country: "Zimbabwe", currency: "Zimbabwean Dollar", code: "ZWL", symbol: "Z$" }
];

export type CurrencyAttribute = "code" | "currency" | "symbol" | "country";