
export type FieldType =
    // Identity / Person
    | "firstName"
    | "lastName"
    | "middleName"
    | "fullName"
    | "prefix"
    | "suffix"
    | "gender"
    | "sex"
    | "jobTitle"
    | "jobArea"
    | "jobType"
    | "jobDescriptor"
    | "bio"
    | "zodiacSign"
    // Internet
    | "email"
    | "username"
    | "password"
    | "url"
    | "domainName"
    | "ipv4"
    | "ipv6"
    | "mac"
    | "userAgent"
    | "emoji"
    | "httpMethod"
    | "httpStatusCode"
    // Phone
    | "phone"
    | "imei"
    // Media
    | "avatar"
    | "imageUrl"
    | "imageUrlPeople"
    | "imageUrlNature"
    | "imageUrlCity"
    | "imageUrlTech"
    | "imageUrlAbstract"
    // Keys
    | "uuid"
    | "nanoid"
    | "autoIncrement"
    | "objectId"
    | "hexString"
    // Location
    | "streetAddress"
    | "secondaryAddress"
    | "city"
    | "state"
    | "stateAbbr"
    | "country"
    | "countryCode"
    | "zipCode"
    | "latitude"
    | "longitude"
    | "timeZone"
    | "directionCardinal"
    // Commerce
    | "company"
    | "companySuffix"
    | "catchPhrase"
    | "buzzPhrase"
    | "productName"
    | "productDescription"
    | "productMaterial"
    | "productAdjective"
    | "department"
    | "price"
    | "sku"
    | "isbn"
    // Finance
    | "accountNumber"
    | "routingNumber"
    | "iban"
    | "bic"
    | "creditCardNumber"
    | "creditCardCvv"
    | "creditCardIssuer"
    | "currencyCode"
    | "currencyName"
    | "currencySymbol"
    | "bitcoinAddress"
    | "ethereumAddress"
    | "transactionType"
    | "amount"
    // Vehicle
    | "vehicle"
    | "vehicleMake"
    | "vehicleModel"
    | "vehicleType"
    | "vehicleFuel"
    | "vehicleColor"
    | "vrm"
    | "vin"
    // Food
    | "food"
    | "foodDish"
    | "foodIngredient"
    | "foodSpice"
    | "foodEthnicCategory"
    // Animal
    | "animalType"
    | "dog"
    | "cat"
    | "bird"
    | "fish"
    | "horse"
    | "insect"
    // Music
    | "musicGenre"
    | "songName"
    // Book
    | "bookTitle"
    | "bookAuthor"
    | "bookGenre"
    | "bookPublisher"
    // Science
    | "chemicalElement"
    | "unit"
    // Hacker / Tech
    | "hackerPhrase"
    | "hackerVerb"
    | "hackerNoun"
    | "hackerAdjective"
    | "hackerAbbreviation"
    // System
    | "fileName"
    | "filePath"
    | "fileExt"
    | "mimeType"
    | "semver"
    | "device"
    | "os"
    // Git
    | "gitBranch"
    | "gitCommitSha"
    | "gitCommitMessage"
    // Airline
    | "airline"
    | "airplane"
    | "airport"
    | "flightNumber"
    | "seatNumber"
    // Sport / Misc
    | "sport"
    // Lorem / Text
    | "word"
    | "words"
    | "sentence"
    | "sentences"
    | "paragraph"
    | "paragraphs"
    | "slug"
    // Primitives
    | "number"
    | "float"
    | "boolean"
    | "date"
    | "pastDate"
    | "futureDate"
    | "recentDate"
    | "soonDate"
    | "weekday"
    | "month"
    | "color"
    | "colorHex"
    | "colorHuman"
    // Custom
    | "static"
    | "enum"
    | "relation";

export type FieldDef = {
    id: string;
    name: string;
    type: FieldType;
    staticValue?: string;
    enumValues?: string;
    min?: number;
    max?: number;
    relationTableId?: string;
    relationFieldId?: string
}

export type TableDef = {
    id: string;
    name: string;
    count: number;
    fields: FieldDef[];
}

export type FieldChildType = {
    type: FieldType; label: string
}

export type FeildGroupType = { label: string; items: FieldChildType[] }